# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.cache/wt [current_project]
set_property parent.project_path C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/CircularCounter.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/CombinedLSFR.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/HighCards.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/Oled_Display.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/anode_display.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/baud_rate_generator.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/blind.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/card_number.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/card_suit.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/debounce_explicit.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/fifo.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/flexible_clk.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/game_flow.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/gameboard.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/hand_value.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/init_animation.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isFOAKChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isFlushChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isFullHouseChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isPairChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isStraightChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isStraightFlushChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isTOAKChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/isTwoPairChecker.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/lose_animation.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/numgen.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/opponent_action.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/pot_amount.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/seedgen.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/suitgen.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/uart_receiver.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/uart_top.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/uart_transmitter.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/who_win.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/win_animation.v
  C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/sources_1/new/poker_test.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/constrs_1/new/basys3_contraints.xdc
set_property used_in_implementation false [get_files C:/Users/puach/Documents/Y2S2/EE2026/poker_uart/poker_uart.srcs/constrs_1/new/basys3_contraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top poker_uart -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef poker_uart.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file poker_uart_utilization_synth.rpt -pb poker_uart_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
